# Generated by Django 5.2.1 on 2025-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_description_post_content_post_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
