# Generated by Django 5.2.2 on 2025-06-16 17:20

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                validators=[
                    blog.validators.validate_spam,
                    blog.validators.CommentMaxLengthValidator(),
                ]
            ),
        ),
    ]
