# Generated by Django 5.2.2 on 2025-06-16 17:03

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(validators=[blog.validators.validate_spam]),
        ),
    ]
