# Generated by Django 5.2.2 on 2025-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at", "title"], name="blog_post_created_e61395_idx"
            ),
        ),
    ]
